force-app/main/default/objects/Internal_Comment__c/Internal_Comment__c.object-meta.xml
<CustomObject>
    <label>Internal Comment</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>Internal Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Internal_Comment__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/InternalCommentHandler.cls
public with sharing class InternalCommentHandler {

    public static void forbidLongBody(List<Internal_Comment__c> comments) {
        for (Internal_Comment__c ic : comments) {
            if(ic.Body__c == null)
                continue;
            for (String row : ic.Body__c.split('\n'))
                if(row.length() > 40){
                    ic.addError('Row out of boundary of 40 characters');
                    break;
                }
        }
    }
}